### ISSUE TITLE
사람 기준으로 모아보는 페이지 제작

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/psybus#12]
## Todo 
- [x] people 페이지 추가
- [x] 각 사람들의 facebook 사진 가져오기
- [ ] 각 people 상세 페이지 추가
- [ ] people, supporters를 묶어 family 메뉴로 이동
