### ISSUE TITLE
beta 버전 릴리즈

### ISSUE THREAD

**Issue by lynn-hong** [lynn-hong/psybus#9]
## Todo
- [x] 메인 페이지 사진 수정
- [x] 메뉴 내비게이션에 icon font 추가(디자인 요소)
- [x] 하단의 버전표기 수정
- [x] 하단에 김무성님 페이스북 페이지 링크 추가
- [x] 스터디그룹 별 스터디 진행내역 view에 괄호 내 파트 정보 추가

**Comment by lynn-hong** [comment]
- v1.0 오픈([관련 블로그 글](http://blog.lynn-hong.com/2018/03/13/psybus.ml-v1.0/))
